name: Build and Distribute

on:
  pull_request:
  push:
    branches:
      - release
      - master
    paths:
      - "**"
      - "!debian/changelog"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}

jobs:
  build_deb:
    name: 'Build DEB'
    uses: s3rj1k/actions-template/.github/workflows/ci-deb-packages-v2.yml@deb
    strategy:
      fail-fast: false
      matrix:
        codename:
          - bookworm
          - bullseye
          - buster
          - stretch
        platform:
          - amd64
    with:
      DEB_BUILD_OPTIONS: "parallel=$(nproc)"
      INSTALL_DEPENDENCIES: true
      PROJECT_NAME: libsilk
      RUNNER: ubuntu-latest
      BASE_IMAGE: signalwire/build-deb-action
      DISTRO_CODENAME: ${{ matrix.codename }}
      PLATFORM: ${{ matrix.platform }}
      BOOTSTRAP_SCRIPT: |
        echo "I am a custom script, look at me!"
        pwd
        ls -lah