name: Build and Distribute #3

on:
  pull_request:
  push:
    branches:
      - release
      - master
    paths:
      - "**"
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}

jobs:
  deb:
    name: 'DEB'
    permissions:
      id-token: write
      contents: read
    uses: signalwire/actions-template/.github/workflows/cicd-docker-build-and-distribute.yml@s3rj1k
    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        os:
          - debian
        version:
          - bullseye
        platform:
          - amd64
          # - arm32v7
    with:
      ARTIFACTS_PATTERN: '.*\.(deb)$'
      DOCKERFILE: .github/docker/${{ matrix.os }}/${{ matrix.version }}/${{ matrix.platform }}/Dockerfile
      MAINTAINER: 'Andrey Volk <andrey@signalwire.com>'
      META_FILE_PATH_PREFIX: /var/www/libsilk/${{ matrix.os }}-${{ matrix.platform }}/${{ github.run_id }}-${{ github.run_number }}
      PLATFORM: ${{ matrix.platform }}
      TARGET_ARTIFACT_NAME: ${{ matrix.os }}-${{ matrix.version }}-${{ matrix.platform }}-artifact
      # UPLOAD_BUILD_ARTIFACTS: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.title, ':upload-artifacts') }}
      UPLOAD_BUILD_ARTIFACTS: true
      META_REPO: signalwire/bamboo_gha_trigger
      META_REPO_BRANCH: libsilk/${{ github.ref_name }}/${{ matrix.os }}/${{ matrix.platform }}
    secrets:
      HOSTNAME: ${{ secrets.HOSTNAME }}
      PROXY_URL: ${{ secrets.PROXY_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      TELEPORT_TOKEN: ${{ secrets.TELEPORT_TOKEN }}
      GH_BOT_DEPLOY_TOKEN: ${{ secrets.PAT }}
